#!/bin/bash

dependency_check() {
  which make >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -yqq make
  fi

  which gcc >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -yqq gcc
  fi

  which g++ >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    if [ "$(os::is_centos)" = "true" ]; then
      pm install -yy gcc-c++
    elif [ "$(os::is_ubuntu)" = "true" ]; then
      pm install -yy g++
    fi
  fi

  which znvm >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro plugin install nvm
  else
    zmicro plugin update nvm
  fi
}

config_profile() {
  znvm env
}

install_nvm() {
  which znvm >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro plugin install nvm
  else
    zmicro plugin update nvm
  fi

  config_profile
}

install_nodejs() {
  zmicro nvm install
}

install_packages() {
  # Depdendency Check
  dependency_check

  # Apply Profile
  config_profile

  # Bin
  export PATH=$(znvm bin):$PATH

  log::info "Install Packages ..."

  install_one() {
    local name=${@:2}
    log::info "  [pacakges: $name] checking ..."

    npm list -g $name >> /dev/null 2>&1
    if [ "$?" = "0" ]; then
      log::info "  [pacakges: $name] installed"
      return
    fi

    log::info "  [pacakges: $name] installing ..."
    npm i -g $name
    if [ "$?" != "0" ]; then
      log::error "  [pacakges: $name] install error"
      return
    fi

    log::success "  [pacakges: $name] install done"
  }

  # bash shell cannot export array as env
  #   stackoverflow: https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable
  config::load_file $PACKAGES_PATH/nodejs/config

  # echo "PACKAGE_NODEJS_DEFAULT_PACKAGES: ${PACKAGE_NODEJS_DEFAULT_PACKAGES[@]}"

  array::each install_one ${PACKAGE_NODEJS_DEFAULT_PACKAGES[@]} 
}

update_packages() {
  # Depdendency Check
  dependency_check

  log::info "Install Packages ..."

  install_one() {
    local name=${@:2}

    log::info "  [update_packages][pacakges: $name] installing ..."
    npm i -g $name
    if [ "$?" != "0" ]; then
      log::error "  [update_packages][pacakges: $name] install error"
      return
    fi

    log::success "  [update_packages][pacakges: $name] install done"
  }

  # bash shell cannot export array as env
  #   stackoverflow: https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable
  config::load_file $PACKAGES_PATH/nodejs/config

  # echo "PACKAGE_NODEJS_DEFAULT_PACKAGES: ${PACKAGE_NODEJS_DEFAULT_PACKAGES[@]}"

  array::each install_one ${PACKAGE_NODEJS_DEFAULT_PACKAGES[@]} 
}

export -f dependency_check

export -f config_profile
export -f install_nvm
export -f install_nodejs

export -f install_packages
export -f update_packages
