#!/bin/bash

pkg::dependency_check() {
  which make >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -yqq make
  fi

  which gcc >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -yqq gcc
  fi

  which g++ >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    if [ "$(os::is_centos)" = "true" ]; then
      pm install -yy gcc-c++
    elif [ "$(os::is_ubuntu)" = "true" ]; then
      pm install -yy g++
    fi
  fi

  which znvm >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro plugin install nvm
  else
    zmicro plugin update nvm
  fi

  which node >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro nvm install
  fi
}

pkg::config_profile() {
  # @TODO zmicro bin
  export PATH=$ZMICRO_BIN_PATH:$PATH
  znvm env
}

pkg::install_version_manager() {
  which znvm >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro plugin install nvm
  else
    zmicro plugin update nvm
  fi
}

pkg::install() {
  # Depdendency Check
  pkg::dependency_check

  pkg::config_profile

  # @TODO node bin
  export PATH=/usr/local/node/bin:$PATH
  pkg::install_packages
}

pkg::install_packages() {
  # Bin
  export PATH=$(znvm bin):$PATH

  log::info "Install Packages ..."

  install_one() {
    local name=${@:2}
    log::info "  [pacakges: $name] checking ..."

    npm list -g $name >> /dev/null 2>&1
    if [ "$?" = "0" ]; then
      log::info "  [pacakges: $name] installed"
      return
    fi

    log::info "  [pacakges: $name] installing ..."
    npm i -g $name
    if [ "$?" != "0" ]; then
      log::error "  [pacakges: $name] install error"
      return
    fi

    log::success "  [pacakges: $name] install done"
  }

  # bash shell cannot export array as env
  #   stackoverflow: https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable
  config::load_file $PACKAGES_PATH/nodejs/config

  # echo "PACKAGE_NODEJS_DEFAULT_PACKAGES: ${PACKAGE_NODEJS_DEFAULT_PACKAGES[@]}"

  array::each install_one ${PACKAGE_NODEJS_DEFAULT_PACKAGES[@]} 
}

pkg::update() {
  pkg::install
}

export -f pkg::dependency_check

export -f pkg::config_profile

export -f pkg::install
export -f pkg::install_version_manager
export -f pkg::install_packages

export -f pkg::update

