#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage install nodejs"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local version=$1

  pkg::install $version

  log::info "Installed NodeJS $(znvm current) ..."
}

run() {
  core $@
}

run $@
